---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_repo_gpg }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb {{ docker_repo_url }} focal stable"
    state: present

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes

- name: Ensure Docker is running
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes

