---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_repo_gpg }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb {{ docker_repo_url }} focal stable"
    state: present

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes

- name: Ensure Docker is running
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes

- name: Pull timurbabs/django image
  community.docker.docker_image:
    name: "timurbabs/django"
    source: pull

- name: Run django_app container
  community.docker.docker_container:
    name: "django_app"
    image: "timurbabs/django"
    state: started
    ports:
      - "8000:8000"
    volumes:
      - "/home/vagrant/django-locallibrary:/app"
    command: /bin/sh -c "pip install django==4.2 python-dotenv && gunicorn locallibrary.wsgi:application --bind 0.0.0.0:8000"

